---
- name: Create Inventory on Tower
  hosts:  localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Create Inventory on Tower
    shell: "tower-cli inventory create -n 'static inventory' --organization ZIONL"
    register: inventory_output

  - name: Find Project Inventory
    find:
      paths: "/var/lib/awx/projects"
      file_type: directory
      patterns: "*inventory"
    register: find_ouput